export const data = [
  {
    "id": 1,
    "title": "iPhone 9",
    "description": "An apple mobile which is nothing like apple",
    "price": 549,
    "rating": 4.69,
    "brand": "Apple",
    "category": "smartphones",
    "stock": 94,
    "thumbnail": "https://i.dummyjson.com/data/products/1/thumbnail.jpg"
  },
  {
    "id": 2,
    "title": "iPhone X",
    "description": "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    "price": 899,
    "rating": 4.44,
    "brand": "Apple",
    "category": "smartphones",
    "stock": 34,
    "thumbnail": "https://i.dummyjson.com/data/products/2/thumbnail.jpg"
  },
  {
    "id": 3,
    "title": "Samsung Universe 9",
    "description": "Samsung's new variant which goes beyond Galaxy to the Universe",
    "price": 1249,
    "rating": 4.09,
    "brand": "Samsung",
    "category": "smartphones",
    "stock": 36,
    "thumbnail": "https://i.dummyjson.com/data/products/3/thumbnail.jpg"
  },
  {
    "id": 4,
    "title": "OPPOF19",
    "description": "OPPO F19 is officially announced on April 2021.",
    "price": 280,
    "rating": 4.3,
    "brand": "OPPO",
    "category": "smartphones",
    "stock": 123,
    "thumbnail": "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
    "outOfStock": true,
  },
  {
    "id": 5,
    "title": "Huawei P30",
    "description": "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    "price": 499,
    "rating": 4.09,
    "brand": "Huawei",
    "category": "smartphones",
    "stock": 32,
    "thumbnail": "https://i.dummyjson.com/data/products/5/thumbnail.jpg"
  },
  {
    "id": 6,
    "title": "MacBook Pro",
    "description": "MacBook Pro 2021 with mini-LED display may launch between September, November",
    "price": 1749,
    "rating": 4.57,
    "brand": "Apple",
    "category": "laptops",
    "stock": 83,
    "thumbnail": "https://i.dummyjson.com/data/products/6/thumbnail.png"
  },
  {
    "id": 7,
    "title": "Samsung Galaxy Book",
    "description": "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    "price": 1499,
    "rating": 4.25,
    "brand": "Samsung",
    "category": "laptops",
    "stock": 50,
    "thumbnail": "https://i.dummyjson.com/data/products/7/thumbnail.jpg"
  },
  {
    "id": 8,
    "title": "Microsoft Surface",
    "description": "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
    "price": 1499,
    "rating": 4.43,
    "brand": "Microsoft Surface",
    "category": "laptops",
    "stock": 68,
    "thumbnail": "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
    "outOfStock": true,
  },
  {
    "id": 9,
    "title": "Infinix INBOOK",
    "description": "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
    "price": 1099,
    "rating": 4.54,
    "brand": "Infinix",
    "category": "laptops",
    "stock": 96,
    "thumbnail": "https://i.dummyjson.com/data/products/9/thumbnail.jpg"
  },
  {
    "id": 10,
    "title": "HP Pavilion",
    "description": "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
    "price": 1099,
    "rating": 4.43,
    "brand": "HP Pavilion",
    "category": "laptops",
    "stock": 89,
    "thumbnail": "https://i.dummyjson.com/data/products/10/thumbnail.jpeg"
  },
  {
    "id": 11,
    "title": "perfume Oil",
    "description": "Mega Discount, Impression of Acqua Di Gio by GiorgioArmani concentrated attar perfume Oil",
    "price": 13,
    "rating": 4.26,
    "brand": "Impression of Acqua Di Gio",
    "category": "fragrances",
    "stock": 65,
    "thumbnail": "https://i.dummyjson.com/data/products/11/thumbnail.jpg",
    "fastDelivery": true
  },
  {
    "id": 12,
    "title": "Brown Perfume",
    "description": "Royal_Mirage Sport Brown Perfume for Men & Women - 120ml",
    "price": 40,
    "rating": 4,
    "brand": "Royal_Mirage",
    "category": "fragrances",
    "stock": 52,
    "thumbnail": "https://i.dummyjson.com/data/products/12/thumbnail.jpg"
  },
  {
    "id": 13,
    "title": "Fog Scent",
    "description": "Product details of Best Fog Scent Xpressio Perfume 100ml For Men cool long lasting perfumes for Men",
    "price": 13,
    "rating": 4.59,
    "brand": "Fog Scent Xpressio",
    "category": "fragrances",
    "stock": 61,
    "thumbnail": "https://i.dummyjson.com/data/products/13/thumbnail.webp",
    "outOfStock": true,
  },
  {
    "id": 14,
    "title": "Non-Alcoholic Perfume",
    "description": "Original Al Munakh® by Mahal Al Musk | Our Impression of Climate | 6ml Non-Alcoholic Concentrated Perfume Oil",
    "price": 120,
    "rating": 4.21,
    "brand": "Al Munakh",
    "category": "fragrances",
    "stock": 114,
    "thumbnail": "https://i.dummyjson.com/data/products/14/thumbnail.jpg"
  },
  {
    "id": 15,
    "title": "Eau De Perfume Spray",
    "description": "Genuine  Al-Rehab spray perfume from UAE/Saudi Arabia/Yemen High Quality",
    "price": 30,
    "rating": 4.7,
    "brand": "Lord - Al-Rehab",
    "category": "fragrances",
    "stock": 105,
    "thumbnail": "https://i.dummyjson.com/data/products/15/thumbnail.jpg",
    "fastDelivery": true
  },
  {
    "id": 16,
    "title": "Hyaluronic Acid Serum",
    "description": "L'OrÃ©al Paris introduces Hyaluron Expert Replumping Serum formulated with 1.5% Hyaluronic Acid",
    "price": 19,
    "rating": 4.83,
    "brand": "L'Oreal Paris",
    "category": "skincare",
    "stock": 110,
    "thumbnail": "https://i.dummyjson.com/data/products/16/thumbnail.jpg"
  },
  {
    "id": 17,
    "title": "Tree Oil 30ml",
    "description": "Tea tree oil contains a number of compounds, including terpinen-4-ol, that have been shown to kill certain bacteria,",
    "price": 12,
    "rating": 4.52,
    "brand": "Hemani Tea",
    "category": "skincare",
    "stock": 78,
    "thumbnail": "https://i.dummyjson.com/data/products/17/thumbnail.jpg"
  },
  {
    "id": 18,
    "title": "Oil Free Moisturizer",
    "description": "Dermive Oil Free Moisturizer with SPF 20 is specifically formulated with ceramides, hyaluronic acid & sunscreen.",
    "price": 40,
    "rating": 4.56,
    "brand": "Dermive",
    "category": "skincare",
    "stock": 88,
    "thumbnail": "https://i.dummyjson.com/data/products/18/thumbnail.jpg",
    "fastDelivery": true
  },
  {
    "id": 19,
    "title": "Skin Beauty Serum.",
    "description": "Product name: rorec collagen hyaluronic acid white face serum riceNet weight: 15 m",
    "price": 46,
    "rating": 4.42,
    "brand": "ROREC White Rice",
    "category": "skincare",
    "stock": 54,
    "thumbnail": "https://i.dummyjson.com/data/products/19/thumbnail.jpg"
  },
  {
    "id": 20,
    "title": "Freckle Cream",
    "description": "Fair & Clear is Pakistan's only pure Freckle cream which helpsfade Freckles, Darkspots and pigments. Mercury level is 0%, so there are no side effects.",
    "price": 70,
    "rating": 4.06,
    "brand": "Fair & Clear",
    "category": "skincare",
    "stock": 140,
    "thumbnail": "https://i.dummyjson.com/data/products/20/thumbnail.jpg"
  },
  {
    "id": 21,
    "title": "Daal Masoor",
    "description": "Fine quality Branded Product Keep in a cool and dry place",
    "price": 20,
    "rating": 4.44,
    "brand": "Saaf & Khaas",
    "category": "groceries",
    "stock": 133,
    "thumbnail": "https://i.dummyjson.com/data/products/21/thumbnail.png",
    "fastDelivery": true
  },
  {
    "id": 22,
    "title": "Elbow Macaroni",
    "description": "Product details of Bake Parlor Big Elbow Macaroni - 400 gm",
    "price": 14,
    "rating": 4.57,
    "brand": "Bake Parlor Big",
    "category": "groceries",
    "stock": 146,
    "thumbnail": "https://i.dummyjson.com/data/products/22/thumbnail.jpg"
  },
  {
    "id": 23,
    "title": "Orange Essence",
    "description": "Specifications of Orange Essence Food Flavour For Cakes and Baking Food Item",
    "price": 14,
    "rating": 4.85,
    "brand": "Baking Food Items",
    "category": "groceries",
    "stock": 26,
    "thumbnail": "https://i.dummyjson.com/data/products/23/thumbnail.jpg"
  },
  {
    "id": 24,
    "title": "cereals muesli",
    "description": "original fauji cereal muesli 250gm box pack original fauji cereals muesli fruit nuts flakes breakfast cereal break fast faujicereals cerels cerel foji fouji",
    "price": 46,
    "rating": 4.94,
    "brand": "fauji",
    "category": "groceries",
    "stock": 113,
    "thumbnail": "https://i.dummyjson.com/data/products/24/thumbnail.jpg",
    "outOfStock": true,
  },
  {
    "id": 25,
    "title": "Gulab Powder",
    "description": "Dry Rose Flower Powder Gulab Powder 50 Gram • Treats Wounds",
    "price": 70,
    "rating": 4.87,
    "brand": "Dry Rose",
    "category": "groceries",
    "stock": 47,
    "thumbnail": "https://i.dummyjson.com/data/products/25/thumbnail.jpg",
    "fastDelivery": true
  },
  {
    "id": 26,
    "title": "Plant Hanger",
    "description": "Boho Decor Plant Hanger For Home Wall Decoration Macrame Wall Hanging Shelf",
    "price": 41,
    "rating": 4.08,
    "brand": "Boho Decor",
    "category": "home-decoration",
    "stock": 131,
    "thumbnail": "https://i.dummyjson.com/data/products/26/thumbnail.jpg"
  },
  {
    "id": 27,
    "title": "Flying Wooden Bird",
    "description": "Package Include 6 Birds with Adhesive Tape Shape: 3D Shaped Wooden Birds Material: Wooden MDF, Laminated 3.5mm",
    "price": 51,
    "rating": 4.41,
    "brand": "Flying Wooden",
    "category": "home-decoration",
    "stock": 17,
    "thumbnail": "https://i.dummyjson.com/data/products/27/thumbnail.webp",
    "outOfStock": true,

  },
  {
    "id": 28,
    "title": "3d Art Lamp",
    "description": "3D led lamp sticker Wall sticker 3d wall art light on/off button  cell operated (included)",
    "price": 20,
    "rating": 4.82,
    "brand": "LED Lights",
    "category": "home-decoration",
    "stock": 54,
    "thumbnail": "https://i.dummyjson.com/data/products/28/thumbnail.jpg"
  },
  {
    "id": 29,
    "title": "Chinese Handcraft",
    "description": "Handcraft Chinese style art luxury palace hotel villa mansion home decor ceramic vase with brass fruit plate",
    "price": 60,
    "rating": 4.44,
    "brand": "luxury palace",
    "category": "home-decoration",
    "stock": 7,
    "thumbnail": "https://i.dummyjson.com/data/products/29/thumbnail.webp",
    "fastDelivery": true
  },
  {
    "id": 30,
    "title": "Key Holder",
    "description": "Attractive DesignMetallic materialFour key hooksReliable & DurablePremium Quality",
    "price": 30,
    "rating": 4.92,
    "brand": "Golden",
    "category": "home-decoration",
    "stock": 54,
    "thumbnail": "https://i.dummyjson.com/data/products/30/thumbnail.jpg"
  }
]

// export const data = [
//   {
//     "id": 1,
//     "title": "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
//     "price": 109.95,
//     "description": "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
//     "category": "men's clothing",
//     "image": "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
//     "rating": {
//       "rate": 3.9,
//       "count": 120
//     },
//     "outOfStock": true,
//     "fastDelivery": false
//   },